controller_list:
  - name: fake_ur5e_controller
    type: $(arg fake_execution_type)
    joints:
      - ur5e_shoulder_pan_joint
      - ur5e_shoulder_lift_joint
      - ur5e_elbow_joint
      - ur5e_wrist_1_joint
      - ur5e_wrist_2_joint
      - ur5e_wrist_3_joint
  - name: fake_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - gripper_finger1_joint
initial:  # Define initial robot poses per group
  - group: ur5e
    pose: home